In [16]:

from ta.trend import ADXIndicator

In [1]:
import main
from sklearn.linear_model import LogisticRegression

c:\Users\vamsi\OneDrive\Desktop\Documents\studies\complete stock market predictor\venv\Lib\site-packages\pandas_ta\__init__.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound


HELLO
106


In [17]:
import importlib
importlib.reload(main)
data=main.data

HELLO
106


In [3]:
x=main.x_reduced_dim

In [4]:
y=main.y_encoded

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2)

In [6]:
x_train.shape

(4574, 6)

In [7]:
x_test.shape

(1144, 6)

In [10]:
model1=LogisticRegression()
model1.fit(x_train,y_train)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [9]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)


,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [11]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(x_train, y_train)

c:\Users\vamsi\OneDrive\Desktop\Documents\studies\complete stock market predictor\venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [09:24:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


,objective,'multi:softprob'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,None
,device,None
,early_stopping_rounds,None
,enable_categorical,False
,eval_metric,'mlogloss'


In [23]:
type(y_predicted)

numpy.ndarray

In [13]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

def evaluate(model, name):
    preds = model.predict(x_test)
    print(f"\n{name} Evaluation")
    print("Accuracy:", accuracy_score(y_test, preds))
    print("F1 Score:", f1_score(y_test, preds, average='weighted'))
    print("Confusion Matrix:\n", confusion_matrix(y_test, preds))
    print("Classification Report:\n", classification_report(y_test, preds))

evaluate(model1, "Logistic Regression")
evaluate(rf_model, "Random Forest")
evaluate(xgb_model, "XGBoost")



Logistic Regression Evaluation
Accuracy: 0.42832167832167833
F1 Score: 0.4272099350849672
Confusion Matrix:
 [[188  75 142]
 [ 94 121 123]
 [147  73 181]]
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.46      0.45       405
           1       0.45      0.36      0.40       338
           2       0.41      0.45      0.43       401

    accuracy                           0.43      1144
   macro avg       0.43      0.42      0.43      1144
weighted avg       0.43      0.43      0.43      1144


Random Forest Evaluation
Accuracy: 0.6748251748251748
F1 Score: 0.6741919471783415
Confusion Matrix:
 [[251  74  80]
 [ 49 246  43]
 [ 70  56 275]]
Classification Report:
               precision    recall  f1-score   support

           0       0.68      0.62      0.65       405
           1       0.65      0.73      0.69       338
           2       0.69      0.69      0.69       401

    accuracy                           0.67     

In [14]:
data=main.data

In [46]:
import numpy as np

def apply_strategy_override(df):
    """
    Applies rule-based logic over model predictions and returns a NumPy array of final strategy predictions.

    Parameters:
    - df: DataFrame containing RSI, ADX, Supertrend_Direction
    - model_preds: Numpy array or Series of model predictions like ['Buy', 'Sell', 'Hold']

    Returns:
    - np.array of final overridden strategy predictions
    """
    final_preds = []

    for i, row in df.iterrows():
        if (row['Supertrend_Direction'] == 1) and (row['RSI'] > 50) and (row['ADX'] > 25):
            final_preds.append("Buy")
        elif row['Supertrend_Direction'] == -1 and (row['RSI'] > 50) and (row['ADX'] > 25):
            final_preds.append("Sell")
        else:
            final_preds.append("Hold")
    
    return np.array(final_preds)


In [18]:
adx = ADXIndicator(high=data['high'], low=data['low'], close=data['close'], window=14)
data['ADX'] = adx.adx()

In [47]:
ok=apply_strategy_override(data)

In [ ]:
ok

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [48]:
print("Accuracy:", accuracy_score(ok, data['result']))
print("F1 Score:", f1_score(ok, data['result'], average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(ok, data['result']))

Accuracy: 0.3071003847499126
F1 Score: 0.38232837007181064
Confusion Matrix:
 [[ 458  350  312]
 [1488 1275 1705]
 [  58   49   23]]


In [39]:
pred_lr = model1.predict(x_test)
pred_rf = rf_model.predict(x_test)
pred_xgb = xgb_model.predict(x_test)


In [40]:
import numpy as np
from scipy.stats import mode

def majority_vote_ensemble(*predictions):
    """
    Accepts multiple model predictions and returns the majority-voted prediction per row.
    """
    preds = np.array(predictions)
    majority_preds, _ = mode(preds, axis=0, keepdims=False)
    return majority_preds


In [43]:
ensemble_preds = majority_vote_ensemble( pred_rf, pred_xgb)


In [45]:
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

print("Ensemble Evaluation")
print("Accuracy:", accuracy_score(y_test, ensemble_preds))
print("F1 Score:", f1_score(y_test, ensemble_preds, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, ensemble_preds))
print("Classification Report:\n", classification_report(y_test, ensemble_preds))


Ensemble Evaluation
Accuracy: 0.6634615384615384
F1 Score: 0.6631652058026635
Confusion Matrix:
 [[278  61  66]
 [ 67 240  31]
 [104  56 241]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.69      0.65       405
           1       0.67      0.71      0.69       338
           2       0.71      0.60      0.65       401

    accuracy                           0.66      1144
   macro avg       0.67      0.67      0.66      1144
weighted avg       0.67      0.66      0.66      1144



In [53]:
import optuna
from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
import numpy as np


def objective(trial):
    param = {
        'objective': 'multi:softprob',
        'eval_metric': 'mlogloss',
        'num_class': len(np.unique(y)),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0),
        'random_state': 42
    }

    model = XGBClassifier(**param, use_label_encoder=False)
    model.fit(x_train, y_train)
    preds = model.predict(x_test)

    return f1_score(y_test, preds, average='macro')


In [54]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)  # You can increase trials to 100+


[I 2025-07-27 10:35:24,431] A new study created in memory with name: no-name-678aece2-1fb0-452b-8498-4e41137e0686
c:\Users\vamsi\OneDrive\Desktop\Documents\studies\complete stock market predictor\venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [10:35:24] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-07-27 10:35:25,792] Trial 0 finished with value: 0.6119660947127592 and parameters: {'learning_rate': 0.18724720315215476, 'max_depth': 9, 'n_estimators': 732, 'min_child_weight': 4, 'gamma': 1.0949965408393902, 'subsample': 0.7018232323713571, 'colsample_bytree': 0.64661788016202, 'reg_alpha': 0.6589880903596061, 'reg_lambda': 0.6228124344733009}. Best is trial 0 with value: 0.6119660947127592.
c:\Users\vamsi\OneDrive\Desktop\Documents\studies\complete stock market predictor\venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [10:35:25] WARNIN

In [56]:
print("Best Trial:")
print(study.best_trial)
print("Best Params:")
print(study.best_params)

# Train final model with best params
best_params = study.best_params
best_params.update({
    'objective': 'multi:softprob',
    'eval_metric': 'mlogloss',
    'num_class': len(np.unique(y)),
    'random_state': 42
})

final_xgb = XGBClassifier(**best_params, use_label_encoder=False)
final_xgb.fit(x_train, y_train)


Best Trial:
FrozenTrial(number=48, state=1, values=[0.6858230310106991], datetime_start=datetime.datetime(2025, 7, 27, 10, 36, 18, 511084), datetime_complete=datetime.datetime(2025, 7, 27, 10, 36, 19, 949690), params={'learning_rate': 0.06272362790584984, 'max_depth': 9, 'n_estimators': 718, 'min_child_weight': 4, 'gamma': 0.20859397249928632, 'subsample': 0.8239590263045817, 'colsample_bytree': 0.8413372605746248, 'reg_alpha': 0.6572570268343788, 'reg_lambda': 0.61560671092879}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'learning_rate': FloatDistribution(high=0.3, log=False, low=0.01, step=None), 'max_depth': IntDistribution(high=10, log=False, low=3, step=1), 'n_estimators': IntDistribution(high=1000, log=False, low=100, step=1), 'min_child_weight': IntDistribution(high=10, log=False, low=1, step=1), 'gamma': FloatDistribution(high=5.0, log=False, low=0.0, step=None), 'subsample': FloatDistribution(high=1.0, log=False, low=0.5, step=None), 'colsample_bytr

c:\Users\vamsi\OneDrive\Desktop\Documents\studies\complete stock market predictor\venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [10:36:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


,objective,'multi:softprob'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,0.8413372605746248
,device,None
,early_stopping_rounds,None
,enable_categorical,False
,eval_metric,'mlogloss'


In [57]:
preds = final_xgb.predict(x_test)

In [58]:
f1_score(y_test, preds, average='macro')

0.6858230310106991

In [62]:
ensemble_preds = majority_vote_ensemble( pred_rf, preds,pred_lr)

In [63]:
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

print("Ensemble Evaluation")
print("Accuracy:", accuracy_score(y_test, ensemble_preds))
print("F1 Score:", f1_score(y_test, ensemble_preds, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, ensemble_preds))
print("Classification Report:\n", classification_report(y_test, ensemble_preds))

Ensemble Evaluation
Accuracy: 0.673951048951049
F1 Score: 0.6737640548810457
Confusion Matrix:
 [[260  69  76]
 [ 52 237  49]
 [ 81  46 274]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.64      0.65       405
           1       0.67      0.70      0.69       338
           2       0.69      0.68      0.69       401

    accuracy                           0.67      1144
   macro avg       0.67      0.68      0.67      1144
weighted avg       0.67      0.67      0.67      1144



In [64]:
# 1. Train base models
rf_preds = rf_model.predict_proba(x_train)
xgb_preds = xgb_model.predict_proba(x_train)

# 2. Concatenate predictions
stacked_input = np.hstack((rf_preds, xgb_preds))  # shape: (n_samples, n_classes*2)

# 3. Train meta model
meta_model = LogisticRegression()
meta_model.fit(stacked_input, y_train)

# For test
rf_test = rf_model.predict_proba(x_test)
xgb_test = xgb_model.predict_proba(x_test)
stacked_test_input = np.hstack((rf_test, xgb_test))

# Final predictions
ensemble_preds = meta_model.predict(stacked_test_input)


array([2, 1, 2, ..., 1, 1, 1], shape=(1144,))

In [67]:
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

print("Ensemble Evaluation")
print("Accuracy:", accuracy_score(y_test, ensemble_preds))
print("F1 Score:", f1_score(y_test, ensemble_preds, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, ensemble_preds))
print("Classification Report:\n", classification_report(y_test, ensemble_preds))

Ensemble Evaluation
Accuracy: 0.6783216783216783
F1 Score: 0.6777502200963316
Confusion Matrix:
 [[252  74  79]
 [ 48 244  46]
 [ 66  55 280]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.62      0.65       405
           1       0.65      0.72      0.69       338
           2       0.69      0.70      0.69       401

    accuracy                           0.68      1144
   macro avg       0.68      0.68      0.68      1144
weighted avg       0.68      0.68      0.68      1144



In [ ]:
# Model Definition
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

ann_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(3, activation='softmax')  # 3 classes
])

ann_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
ann_model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.1, verbose=0)


In [72]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split

from sklearn.metrics import classification_report

# Convert data to PyTorch tensors (if not already)
X_tensor = torch.tensor(x_train, dtype=torch.float32)
y_tensor = torch.tensor(y_train, dtype=torch.long)

# Create Dataset and DataLoader
dataset = TensorDataset(X_tensor, y_tensor)
train_size = int(0.9 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

# Define the ANN model
class ANNModel(nn.Module):
    def __init__(self, input_dim):
        super(ANNModel, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 3),  # 3 classes
        )

    def forward(self, x):
        return self.network(x)

# Initialize
model = ANNModel(input_dim=x_train.shape[1])
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
epochs = 100
for epoch in range(epochs):
    model.train()
    total_loss = 0
    for xb, yb in train_loader:
        optimizer.zero_grad()
        out = model(xb)
        loss = criterion(out, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

model.eval()
with torch.no_grad():
    X_test_tensor = torch.tensor(x_test, dtype=torch.float32)
    outputs = model(X_test_tensor)
    predictions = torch.argmax(outputs, dim=1)
    print(classification_report(y_test, predictions))


Epoch 10, Loss: 130.4615
Epoch 20, Loss: 127.8010
Epoch 30, Loss: 124.7735
Epoch 40, Loss: 123.2228
Epoch 50, Loss: 121.9847
Epoch 60, Loss: 119.5544
Epoch 70, Loss: 119.4209
Epoch 80, Loss: 117.7217
Epoch 90, Loss: 116.8840
Epoch 100, Loss: 114.8186
              precision    recall  f1-score   support

           0       0.52      0.39      0.45       405
           1       0.53      0.61      0.57       338
           2       0.52      0.59      0.55       401

    accuracy                           0.52      1144
   macro avg       0.52      0.53      0.52      1144
weighted avg       0.52      0.52      0.52      1144



In [75]:
from sklearn.neighbors import KNeighborsClassifier
models=KNeighborsClassifier()
models.fit(x_train,y_train)
okk=models.predict(x_test)

In [76]:
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

print("Ensemble Evaluation")
print("Accuracy:", accuracy_score(y_test, okk))
print("F1 Score:", f1_score(y_test, okk, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, okk))
print("Classification Report:\n", classification_report(y_test, okk))

Ensemble Evaluation
Accuracy: 0.6468531468531469
F1 Score: 0.6463803859918299
Confusion Matrix:
 [[270  68  67]
 [ 62 233  43]
 [ 91  73 237]]
Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.67      0.65       405
           1       0.62      0.69      0.65       338
           2       0.68      0.59      0.63       401

    accuracy                           0.65      1144
   macro avg       0.65      0.65      0.65      1144
weighted avg       0.65      0.65      0.65      1144



In [77]:
x=main.x

In [78]:
x

,ATR,Supertrend_Direction,RSI,MACD,Day of the week,Is Weekend,Month,hour,high_liquidity
37,9.386429,1,62.153490,10.613872,1,False,22,6,0
38,9.578357,1,56.566546,10.613872,1,False,22,6,0
39,10.202214,-1,43.861039,8.598401,1,False,22,7,0
40,10.599857,-1,46.340775,6.773641,1,False,22,7,0
41,11.015429,-1,51.969966,5.932092,1,False,22,7,0
...,...,...,...,...,...,...,...,...,...
5842,2.158786,-1,36.676534,-0.891610,4,True,18,19,0
5843,2.016929,-1,43.561901,-0.908368,4,True,18,20,0
5844,1.856786,-1,43.171129,-0.921198,4,True,18,20,0
5845,1.927286,-1,48.112163,-0.821675,4,True,18,20,0
